### ISSUE TITLE
无法筛选出vant组件内部内部调用的vant组件

### ISSUE THREAD

**Issue by worldsoon** [cafehaus/vant-tree-shaking#2]
![image](https://github.com/user-attachments/assets/93d2f0d8-fa58-4d36-8ddf-338703c19682)
![image](https://github.com/user-attachments/assets/73b1d9ce-f1d9-44f3-bbb1-13db79046c2e)

内部调用的vant组件的组件路径是不带vant-前缀的

**Comment by cafehaus** [comment]
核对了下vant所有组件，就只有你截图的 picker 那一个组件引用外部组件没加 van-，最新版本 1.0.4 已经兼容处理
